version: "3.3"
services:
  bind:
    build: ./bind
    volumes:
      - ./conf:/etc/bind
    ports:
      - "53:53/udp"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  sender:
    build: ./sender
    ports:
      - "587:587"
    dns:
      - 10.5.0.4
    tty: true
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

  receiver:
    build: ./receiver
    volumes:
      - ./mailbox:/home/tester/Maildir
    ports:
      - "25:25"
      - "110:110"
    dns:
      - 10.5.0.4
    tty: true
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16

